rewrite instantassist

diff --git a/instantassist b/instantassist
--- a/instantassist
+++ b/instantassist
@@ -1,32 +1,21 @@
 #!/usr/bin/env dash
+
 # main menu to access instantASSIST
 
-PAPERAPP=$(cat /usr/share/instantassist/menus/apps | instantmenu -i -p instantASSIST -n -h 32 -F)
-[ -z "$PAPERAPP" ] && exit
+ASSIST=$(cat /usr/share/instantassist/cache/cache | instantmenu -i -p instantASSIST -n -h 32 -F -ct | grep '^.')
 
-TEMP=$(ls /usr/share/instantassist/menus/dm/$PAPERAPP*.sh | sed 's/^.*\///g' |
-    grep -o '^[^\.]*' | grep "^$PAPERAPP" | grep -o '.$' | uniq)
+[ -z "$ASSIST" ] && exit
 
-exescript() {
-    [ -e /usr/share/instantassist/menus/dm/$1.sh ] &&
-        echo "executing $1" &&
-        bash /usr/share/instantassist/menus/dm/$1.sh && exit
-}
-
-if [ -n "$TEMP" ] && [ "$(echo "$TEMP" | wc -l)" -gt "1" ]; then
-    if [ -e /usr/share/instantassist/menus/dm/$PAPERAPP$PAPERAPP.sh ]; then
-        APP2=$(echo "$TEMP" | instantmenu -i -n -h 32 -F)
-    else
-        APP2=$(echo "$TEMP" | instantmenu -i -n -h 32 -F)
-    fi
-
-    if [ -n "$APP2" ]; then
-        exescript "$PAPERAPP$APP2"
-    else
-        exescript "$PAPERAPP$PAPERAPP"
-        exescript "$PAPERAPP"
-    fi
+if [ -d /usr/share/instantassist/assists/"$ASSIST" ]; then
+    ASSIST2="$(cat /usr/share/instantassist/cache/"$ASSIST" | instantmenu -i -p instantASSIST -n -h 32 -F -ct | grep '^.')"
+    [ -z "$ASSIST2" ] && exit
+    SCRIPTPATH=/usr/share/instantassist/assists/"$ASSIST/$ASSIST2"
 else
-    exescript "$PAPERAPP$PAPERAPP"
-    exescript "$PAPERAPP"
+    if ! [ -e /usr/share/instantassist/assists/"$PAPERAPP" ]; then
+        echo "assist not found"
+        exit
+    fi
+    SCRIPTPATH=/usr/share/instantassist/assists/"$ASSIST"
 fi
+
+"$SCRIPTPATH"
